# Generated by Django 5.0.1 on 2024-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_medicalspecialty_healthspecialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalspecialty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medical_specialty_images/'),
        ),
    ]
