# Generated by Django 5.0.1 on 2024-01-13 17:09

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_medicalspecialty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalspecialty',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 500], upload_to='medical_specialty_images/'),
        ),
    ]
